#Raw terminal commands
# docker run -d --network mongo-network --name mongoDb \
# -e MONGO_INITDB_ROOT_USERNAME=mongoadmin \
# -e MONGO_INITDB_ROOT_PASSWORD=secret \
# -p 27017:27017 \
# mongo

# docker run -d --network mongo-network --name express \
# -e ME_CONFIG_MONGODB_SERVER=mongoDb \
# -e ME_CONFIG_MONGODB_ADMINPASSWORD=secret \
# -e ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin \
# -p 8081:8081 \
# mongo-express

# Run mongo and mongo-express
#network will be auto created
version: "0.1"

services:
  mongoDb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDb
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      # ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:localhost@mongoDb:27017
